applications/mall/src/main/java/cn/jastz/mall/form/MallStoreAddSkuForm.java
package cn.jastz.mall.form;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

/**
 * @author zhiwen
 */
public class MallStoreAddSkuForm {

    private int storeId;
    private List<MallStoreAddSkuItem> storeAddSkuItems;

    public List<Integer> skuIdList() {
        List<Integer> skuIdList = Lists.newArrayList();
        storeAddSkuItems.forEach(storeAddSkuItem -> skuIdList.add(storeAddSkuItem.getSkuId()));
        return skuIdList;
    }

    public Map<Integer, MallStoreAddSkuItem> map() {
        Map<Integer, MallStoreAddSkuItem> map = Maps.newHashMap();
        storeAddSkuItems.forEach(storeAddSkuItem -> map.put(storeAddSkuItem.getSkuId(), storeAddSkuItem));
        return map;
    }

    /**
     * getter and setter
     */
    public int getStoreId() {
        return storeId;
    }

    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }

    public List<MallStoreAddSkuItem> getStoreAddSkuItems() {
        return storeAddSkuItems;
    }

    public void setStoreAddSkuItems(List<MallStoreAddSkuItem> storeAddSkuItems) {
        this.storeAddSkuItems = storeAddSkuItems;
    }


    public static class MallStoreAddSkuItem {
        private int skuId;
        private BigDecimal storePrice;
        private Long stock;

        public int getSkuId() {
            return skuId;
        }

        public void setSkuId(int skuId) {
            this.skuId = skuId;
        }

        public BigDecimal getStorePrice() {
            return storePrice;
        }

        public void setStorePrice(BigDecimal storePrice) {
            this.storePrice = storePrice;
        }

        public Long getStock() {
            return stock;
        }

        public void setStock(Long stock) {
            this.stock = stock;
        }
    }
}

applications/mall/src/main/java/cn/jastz/mall/vo/StoreSkuProductStockVo.java
package cn.jastz.mall.vo;

import cn.jastz.product.entity.Product;
import cn.jastz.product.vo.SkuProductVo;
import cn.jastz.store.entity.StoreSkuStock;

/**
 * @author zhiwen
 */
public class StoreSkuProductStockVo extends StoreSkuStock {
    private SkuProductVo skuProductVo;

    public SkuProductVo getSkuProductVo() {
        return skuProductVo;
    }

    public void setSkuProductVo(SkuProductVo skuProductVo) {
        this.skuProductVo = skuProductVo;
    }

    public String getSkuDes() {
        return String.format("%s-%s", skuProductVo.getSkuCode(), skuProductVo.getPrice());
    }
}

applications/mall/src/main/java/cn/jastz/mall/controller/ProductController.java
package cn.jastz.mall.controller;

import cn.jastz.product.client.ProductClient;
import cn.jastz.product.vo.ProductSkuVo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

/**
 * @author zhiwen
 */
@Controller
public class ProductController {
    @Autowired
    private ProductClient productClient;

    @ResponseBody
    @GetMapping("product/sku/vo/list")
    public List<ProductSkuVo> queryProductSkuVoList() {
        return productClient.queryProductSkuVoList();
    }
}

applications/mall/src/main/java/cn/jastz/mall/controller/StoreController.java
package cn.jastz.mall.controller;

import cn.jastz.mall.form.MallStoreAddSkuForm;
import cn.jastz.mall.result.MallResult;
import cn.jastz.mall.service.StoreService;
import cn.jastz.page.domain.Page;
import cn.jastz.page.domain.PageRequest;
import cn.jastz.store.client.StoreClient;
import cn.jastz.store.client.StoreSkuStockClient;
import cn.jastz.store.entity.Store;
import cn.jastz.store.form.StoreAddForm;
import cn.jastz.store.form.StoreSkuStockForm;
import cn.jastz.store.result.StoreResult;
import me.jastz.common.json.result.IResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

/**
 * @author zhiwen
 */
@Controller
public class StoreController {
    @Autowired
    private StoreClient storeClient;

    @Autowired
    private StoreSkuStockClient storeSkuStockClient;

    @Autowired
    private StoreService storeService;

    @GetMapping("store")
    public String addStore() {
        return "store/add";
    }

    @GetMapping("store/page/{page}")
    public String queryPage(Model model, @PathVariable("page") int page, @RequestParam(defaultValue = "12", name = "size") int size) {
        Page<Store> pageStore = storeClient.queryPage(PageRequest.of(page - 1, size));
        model.addAttribute("page", pageStore);
        return "store/page";
    }

    @ResponseBody
    @PostMapping("store")
    public IResult addStore(StoreAddForm storeAddForm) {
        if (storeClient.addStore(storeAddForm).getResultCode() == StoreResult.SUCCESS.getResultCode()) {
            return MallResult.SUCCESS;
        }
        return MallResult.FAIL;
    }

    @ResponseBody
    @PostMapping("store/sku/batch/add")
    public IResult batchAddStoreSku(MallStoreAddSkuForm mallStoreAddSkuForm) {
        return storeService.batchAddStoreSku(mallStoreAddSkuForm);
    }

    @GetMapping("store/sku/stock/{storeId}")
    public String queryAllStoreSkuStockByStoreId(@PathVariable("storeId") int storeId, Model model) {
        model.addAttribute("list", storeService.queryAllStoreSkuStockByStoreId(storeId));
        return "store/sku/list";
    }

    @ResponseBody
    @PostMapping("store/sku/stock/updateSkuStock")
    public IResult updateSkuStock(@RequestBody StoreSkuStockForm storeSkuStockForm) {
        if (MallResult.SUCCESS.getResultCode() == storeSkuStockClient.updateSkuStock(storeSkuStockForm).getResultCode()) {
            return MallResult.SUCCESS;
        }
        return MallResult.FAIL;
    }

    @ResponseBody
    @PostMapping("store/sku/stock/updateSkuPrice")
    public IResult updateSkuPrice(@RequestBody StoreSkuStockForm storeSkuStockForm) {
        if (storeSkuStockClient.updateSkuPrice(storeSkuStockForm).getResultCode() == MallResult.SUCCESS.getResultCode()) {
            return MallResult.SUCCESS;
        }
        return MallResult.FAIL;
    }
}

applications/mall/src/main/resources/templates/store/add.ftl
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Store</title>
</head>
<body>
<form action="/store" method="post">
    store name:<input type="text" name="storeName">
    store address:<input type="text" name="address">
    <button type="submit">提交</button>
</form>
</body>
</html>

applications/mall/src/main/resources/templates/store/page.ftl
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Store</title>
</head>
<body>
<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">名称</th>
        <th scope="col">地址</th>
        <th scope="col">操作</th>
    </tr>
    </thead>
    <tbody>
<#list page.getContent() as store>
<tr>
    <td>${store?index}</td>
    <td>${store.storeName}</td>
    <td>${store.address}</td>
    <td><a href="javascript:void(0);" onclick="showAddSku(this,'${store.storeName}','${store.storeId}')">添加sku</a>|<a
            href="${requestContext.getContextPath()}/store/sku/stock/${store.storeId}">sku列表</a></td>
</tr>
</#list>
    </tbody>
</table>
<div id="addStoreSkuForm" style="display: none">
    <div class="box-body">
        <input type="hidden" name="storeId">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 control-label">点位名称</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="storeName" placeholder="点位名称">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 control-label">SKU</label>
            <div class="col-sm-10">
                <div class="form-row">
                    <div class="col">
                        <select name="productId" class="form-control"></select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<javascript>
    <script type="text/javascript">
        function showAddSku(element, storeName, storeId) {
            var id = "addStoreSkuModal";
            var formName = "addStoreSkuForm";
            var formAction = "${requestContext.getContextPath()}/store/sku/batch/add";
            $(element).myModal({
                "id": id,
                "title": "添加点位SKU",
                "formName": formName,
                "formAction": formAction,
                "bodyHtml": $("#addStoreSkuForm").html()
            });
            $("form[name='" + formName + "']").find("input[name='storeId']").val(storeId);
            $("form[name='" + formName + "']").find("input[name='storeName']").val(storeName).prop("disabled", true);
            $("form[name='" + formName + "']").find("select[name='productId']").productSku();
        }

    </script>
</javascript>
</body>
</html>

applications/mall/src/main/resources/templates/store/sku/list.ftl
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>门店SKU列表</title>
</head>
<body>
<table class="table">
    <thead>
    <tr>
        <th>编号</th>
        <th>商品名称</th>
        <th>描述</th>
        <th>库存</th>
        <th>售价</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
        <#list list as sku>
        <tr>
            <td>${sku.skuId}</td>
            <td>${sku.skuProductVo.product.productName!""}</td>
            <td>${sku.skuDes!""}</td>
            <td>${sku.skuStock}</td>
            <td>${sku.skuPrice}</td>
            <td><a href="javascript:void(0);"
                   onclick="showUpdateSkuStock(this,'${sku.storeId}','${sku.productId}','${sku.skuId}','${sku.skuDes}')">上库存</a>|<a
                    href=" javascript:void(0);"
                    onclick="showUpdateSkuPrice(this,'${sku.storeId}','${sku.productId}','${sku.skuId}','${sku.skuDes}','${sku.skuPrice}')">改价</a>
            </td>
        </tr>
        </#list>
    </tbody>
</table>
<div id="updateSkuStock" style="display: none">
    <div class="box-body">
        <input type="hidden" name="storeId">
        <input type="hidden" name="productId">
        <input type="hidden" name="skuId">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 control-label">sku描述</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="skuDesc" placeholder="sku描述">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 control-label">上架库存数</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="skuStock" placeholder="上架库存数">
            </div>
        </div>
    </div>
</div>
<div id="updateSkuPrice" style="display: none">
    <div class="box-body">
        <input type="hidden" name="storeId">
        <input type="hidden" name="productId">
        <input type="hidden" name="skuId">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 control-label">sku描述</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="skuDesc" placeholder="sku描述">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 control-label">价格</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="price" placeholder="价格">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 control-label">新价格</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="skuPrice" placeholder="新价格">
            </div>
        </div>
    </div>
</div>
</body>
<javascript>
    <script type="text/javascript">
        function showUpdateSkuStock(element, storeId, productId, skuId, skuDesc) {
            var id = "updateSkuStockModal";
            var formName = "updateSkuStockForm";
            var formAction = "${requestContext.getContextPath()}/store/sku/stock/updateSkuStock";
            $(element).myModal({
                "id": id,
                "title": "添加点位SKU",
                "formName": formName,
                "formAction": formAction,
                "bodyHtml": $("#updateSkuStock").html()
            });
            $("form[name='" + formName + "']").find("input[name='storeId']").val(storeId);
            $("form[name='" + formName + "']").find("input[name='productId']").val(productId);
            $("form[name='" + formName + "']").find("input[name='skuId']").val(skuId);
            $("form[name='" + formName + "']").find("input[name='skuDesc']").val(skuDesc).prop("disabled", true);
        }

        function showUpdateSkuPrice(element, storeId, productId, skuId, skuDesc, price) {
            var id = "updateSkuPriceModal";
            var formName = "updateSkuPriceForm";
            var formAction = "${requestContext.getContextPath()}/store/sku/stock/updateSkuPrice";
            $(element).myModal({
                "id": id,
                "title": "添加点位SKU",
                "formName": formName,
                "formAction": formAction,
                "bodyHtml": $("#updateSkuPrice").html()
            });
            $("form[name='" + formName + "']").find("input[name='storeId']").val(storeId);
            $("form[name='" + formName + "']").find("input[name='productId']").val(productId);
            $("form[name='" + formName + "']").find("input[name='skuId']").val(skuId);
            $("form[name='" + formName + "']").find("input[name='skuDesc']").val(skuDesc).prop("disabled", true);
            $("form[name='" + formName + "']").find("input[name='price']").val(price).prop("disabled", true);
        }
    </script>
</javascript>
</html>